jenkins:
  systemMessage: "Wishes Tracking Pipeline"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
        - id: "pape45"
          password: "${PAPE_PASSWORD}"
  
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Administer:pape45"
        - "Overall/Read:authenticated"
        - "Overall/SystemRead:pape45"
        - "Job/Build:pape45"
        - "Job/Configure:pape45"
        - "Job/Create:pape45"
        - "Job/Delete:pape45"
        - "Job/Read:pape45"
        - "Job/Workspace:pape45"
        - "Agent/Build:pape45"
        - "Run/Replay:pape45"
        - "Run/Update:pape45"