jenkins:
  systemMessage: "Wishes Tracking Pipeline"
  numExecutors: 2
  scmCheckoutRetryCount: 3
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
        - id: "pape45"
          password: "${PAPE_PASSWORD}"
  
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Administer:pape"
        - "Overall/Read:authenticated"
        - "Job/Build:pape"
        - "Job/Configure:pape"
        - "Job/Create:pape"
        - "Job/Delete:pape"
        - "Job/Read:pape"